import {
  Shield,
  Lock,
  Database,
  MessageSquare,
  Settings,
  Plus,
  Search,
  FileText,
  Heart,
  Activity,
  Trash2,
  Edit,
  X,
  Check,
  ChevronRight,
  ChevronDown,
  User,
  LogOut,
  Moon,
  Sun,
  Upload,
  Download,
  RefreshCw,
  Link2,
  Unlink,
  AlertCircle,
  CheckCircle,
  Clock,
  Tag,
  Filter,
  MoreVertical,
  Send,
  Bot,
  Sparkles,
  Folder,
  File,
  Stethoscope,
  Apple,
  Watch,
  Loader2,
  ArrowLeft,
  Home,
  type LucideIcon,
} from "lucide-react"

export {
  Shield,
  Lock,
  Database,
  MessageSquare,
  Settings,
  Plus,
  Search,
  FileText,
  Heart,
  Activity,
  Trash2,
  Edit,
  X,
  Check,
  ChevronRight,
  ChevronDown,
  User,
  LogOut,
  Moon,
  Sun,
  Upload,
  Download,
  RefreshCw,
  Link2,
  Unlink,
  AlertCircle,
  CheckCircle,
  Clock,
  Tag,
  Filter,
  MoreVertical,
  Send,
  Bot,
  Sparkles,
  Folder,
  File,
  Stethoscope,
  Apple,
  Watch,
  Loader2,
  ArrowLeft,
  Home,
  type LucideIcon,
}

// Custom vault logo
export function VaultLogo({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" className={className}>
      <rect x="4" y="8" width="24" height="20" rx="2" stroke="currentColor" strokeWidth="2" />
      <path d="M16 4V8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      <circle cx="16" cy="18" r="3" stroke="currentColor" strokeWidth="2" />
      <path d="M16 21V24" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
    </svg>
  )
}
